galaxy_info:
  author: Klusters
  description: Check Elasticsearch Cluster health
  company: ''

  license: license MIT

  min_ansible_version: 2.9

  galaxy_tags:
  - elasticsearch

  platforms:
  - name: EL
    versions:
    - 8
    - 7
  - name: Ubuntu
    versions:
      - xenial
      - bionic

dependencies: []