---

- name: set fact manage_native_users to true
  set_fact: manage_native_users=true
  when: es_users is defined and es_users.native is defined and es_users.native.keys() | list | length > 0

- name: set fact manage_native_roles to true
  set_fact: manage_native_roles=true
  when: es_roles is defined and es_roles.native is defined and es_roles.native.keys() | list | length > 0

#--------------------------SECRETS MANAGEMENT-------------------------------------

- name: Manage ES credentials with secrets
  include: secrets/secrets.yml
  when: es_secrets_mode_enabled | bool
  run_once: yes

#-----------------------------NATIVE REALM----------------------------------------

- name: realms/native/users.yml
  include: realms/native/users.yml
  when: manage_native_users | bool
  run_once: yes

- name: realms/native/roles.yml
  include: realms/native/roles.yml
  when: manage_native_roles | bool
  run_once: yes

...