---

- name: Create Snapshot Repositories
  uri:
    url: "{{ es_api_uri }}/{{ es_api_snapshots }}/{{ item.name }}?verify=false"
    method: PUT
    body_format: json
    body:
      type: "{{ item.type }}"
      settings: "{{ item.settings }}"
    status_code: 200
    user: "{{ es_api_basic_auth_username }}"
    password: "{{ es_api_basic_auth_password }}"
    force_basic_auth: yes
    validate_certs: "{{ es_validate_certs }}"
  when: es_create_repositories
  with_items: "{{ es_repositories }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create Snapshots
  uri:
    url: "{{ es_api_uri }}/{{ es_api_snapshots }}/{{ item.repository }}/{{ item.name | urlencode | regex_replace('/', '%2F') }}"
    method: PUT
    body_format: json
    body: "{{ item.settings }}"
    status_code: 200
    user: "{{ es_api_basic_auth_username }}"
    password: "{{ es_api_basic_auth_password }}"
    force_basic_auth: yes
    validate_certs: "{{ es_validate_certs }}"
  when: es_create_snapshots
  with_items: "{{ es_snapshots_to_create }}"
  loop_control:
    label: "{{ item.name }}"

- name: Restore Snapshots
  uri:
    url: "{{ es_api_uri }}/{{ es_api_snapshots }}/{{ item.repository }}/{{ item.name }}/_restore?master_timeout=170s"
    method: POST
    body_format: json
    body: "{{ item.settings }}"
    status_code: 200
    timeout: 180
    user: "{{ es_api_basic_auth_username }}"
    password: "{{ es_api_basic_auth_password }}"
    force_basic_auth: yes
    validate_certs: "{{ es_validate_certs }}"
  when: es_restore_snapshots
  with_items: "{{ es_snapshots_to_restore }}"
  loop_control:
    label: "{{ item.name }}"
