---

es_api_basic_auth_password: 'changeme'
es_api_basic_auth_username: 'elastic'

es_api_scheme: 'https'
es_api_host: "localhost"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_security_api: '_security'

es_validate_certs: no

es_delete_unmanaged_native: true

es_roles:
  native:
    sample_role_1:
      cluster: []
      indices:
      - names: 'sample-index-1-*'
        privileges:
        - create_index
        - write
    sample_role_2:
      cluster: ['monitor']
      indices:
      - names: 'dummy-index-*'
        privileges:
        - read

#### SYNTAX :
# es_roles:
#   native:
#     rolename_1:
#       cluster: ['cluster_permission_1', 'cluster_persmission_2']
#       indices:
#       - names: 'indice_name'
#         privileges:
#         - indice_privilege_1
#         - indice_privilege_2
#
# https://github.com/elastic/ansible-elasticsearch/blob/7.9.3/README.md#installing-x-pack-features

es_users:
  native:
    dummy_user_1:
      password: 'dummy_password_1'
      roles:
      - sample_role_1
    dummy_user_2:
      password: 'dummy_password_2'
      roles:
      - sample_role_2

    metricbeat_collect_es:
      password: 'dummy_password_3'
      roles:
      - remote_monitoring_collector
      - enrich_user

#### SYNTAX :
# es_users:
#   native:
#     username_1:
#       password: '{% if "username_1" in es_users_secret %}{{ es_users_secret["username_1"] }}{% else %}{{ lookup("password", "/dev/null chars=ascii_letters,digits" ) }}{% endif %}'
#       roles:
#       - user_1_role_1 # from es_roles.yml or system default roles
#       - user_1_role_2 # from es_roles.yml or system default roles
#    
#     username_2:
#       password: '{% if "username_2" in es_users_secret %}{{ es_users_secret["username_2"] }}{% else %}{{ lookup("password", "/dev/null chars=ascii_letters,digits" ) }}{% endif %}'
#       roles:
#       - user_2_role_1 # from es_roles.yml or system default roles
#       - user_2_role_2 # from es_roles.yml or system default roles
#
# https://github.com/elastic/ansible-elasticsearch/blob/7.9.3/README.md#installing-x-pack-features