---

es_api_scheme: "http"
es_api_host: "localhost"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_api_snapshots: "_snapshot"
es_api_basic_auth_username: 'elastic'
es_api_basic_auth_password: 'changeme'

es_validate_certs: no
es_create_repositories: yes

es_repositories:
  - name: "fs_default_name"
    type: "fs"
    settings:
      location: "/my_fs_backup_location"
      compress: "true"
      chunk_size: null
      max_restore_bytes_per_sec: "40mb"
      max_snapshot_bytes_per_sec: "40mb"
      readonly: "false"

  # - name: "s3_default_name"
  #   type: "s3"
  #   settings:
  #     endpoint: s3.amazonaws.com
  #     protocol: https
  #     proxy.host: "my_http_proxy_host"
  #     proxy.port: "my_http_proxy_port"
  #     read_timeout: 50s
  #     max_retries: 3
  #     use_throttle_retries: "true"
  #     path_style_access: "false"
  #     disable_chunked_encoding: "false"
  #     bucket: 'my_bucket'
  #     client: 'default'
  #     base_path: ''
  #     chunk_size: '1GB'
  #     compress: 'false'
  #     max_restore_bytes_per_sec: '40mb'
  #     max_snapshot_bytes_per_sec: '40mb'
  #     readonly: 'false'
  #     server_side_encryption: 'false'
  #     canned_acl: 'private'
  #     storage_class: 'standard'

es_create_snapshots: no

es_snapshots_to_create:
  - name: <fs-snapshot-{now/d}>
    repository: "fs_default_name"
    settings:
      indices: ["*"]
      ignore_unavailable: "true"
      include_global_state: "false"
      metadata:
        taken_by: "me"
        taken_because: "i wanted to"

  # - name: <s3-snapshot-{now/d}>
  #   repository: "s3_default_name"
  #   settings:
  #     indices: ["index_3", "index_4"]
  #     ignore_unavailable: "true"
  #     include_global_state: "false"
  #     metadata:
  #       taken_by: "me"
  #       taken_because: "i wanted to"

es_restore_snapshots: no

es_snapshots_to_restore: []
  # - name: 'snapshot-2020.06.24'
  #   repository: 'cert'
  #   settings:
  #     indices: "index_1,index_2"
  #     ignore_unavailable: 'true'
  #     include_global_state: 'false'
  #     rename_pattern: "index_(.+)"
  #     rename_replacement: "restored_index_$1"
  #     include_aliases: 'false'

...