---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint

platforms:
- name: elasticsearch
  image: elasticsearch:${MOLECULE_ES_VERSION:-7.9.2}
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  published_ports:
  - 9200:9200
  env:
    discovery.type: single-node
  command: eswrapper
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
