---

- name: Converge
  hosts: localhost
  connection: local
  pre_tasks:
  - name: Wait for elasticsearch to startup
    wait_for: host={{ es_api_host }} port={{ es_api_port }} delay=30 connect_timeout=1 timeout=120

  roles:
  - role: klusters.elasticsearch.snapshots
    vars:
      es_create_snapshots: yes
      es_restore_snapshots: no
