---

es_api_scheme: 'https'
es_api_host: 'localhost'
es_cluster_name: 'ci-cluster'
es_k8s_namespace: 'default'

es_api_basic_auth_username: 'elastic'
es_api_basic_auth_password: 'ci-dummy-password'


found_k8s_secrets: "{{ lookup('k8s', kind='Secret', namespace=es_k8s_namespace, label_selector='purpose=es_users,es_cluster=' + es_cluster_name) | json_query('[*].metadata.name')}}"

es_secrets_mode_enabled: yes
es_secrets_mode: k8s

...